version: '3.8'
services:
  db:
    image: postgres:15.3-alpine
    # restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '${PGPORT}:5432'
    volumes: 
      - pg-essential:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  pg-essential:
    driver: local